export enum RightsEnum {
  SEND_MESSAGES = "SEND_MESSAGES",
  SEND_ATTACHMENTS = "SEND_ATTACHMENTS",
  DELETE_MESSAGES = "DELETE_MESSAGES",
  CHANGE_MESSAGES = "CHANGE_MESSAGES",
  ADD_USERS = "ADD_USERS",
  DELETE_USERS = "DELETE_USERS",
  CHANGE_USER_RIGHTS = "CHANGE_USER_RIGHTS",
  CHANGE_ROOM = "CHANGE_ROOM",
  DELETE_ROOM = "DELETE_ROOM",
  LEAVE_ROOM = "LEAVE_ROOM"
}
